version: "3.8"

services:
    mariadb:
      container_name: mariadb
      networks:
        - inception
      build: 
        context: requirements/mariadb
        dockerfile: Dockerfile
        args:
          SQL_DATABASE: ${SQL_DATABASE}
          SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
          SQL_USER: ${SQL_USER}
          SQL_PASSWORD: ${SQL_PASSWORD}
      env_file: 
        - .env
      volumes:
        - volume_mariadb:/var/lib/mysql
      restart: unless-stopped
      expose:
        - "3306"

    nginx:
        container_name: nginx
        volumes:
          - volume_wordpress:/var/www/wordpress
        networks:
          - inception
        depends_on:
         - wordpress
        build:
          context: requirements/nginx
          dockerfile: Dockerfile
        env_file: .env
        ports:
          - "443:443"
        restart: unless-stopped

    wordpress:
      container_name: wordpress
      env_file: .env
      volumes:
        - volume_wordpress:/var/www/wordpress
      networks:
        - inception
      build:
        context: requirements/wordpress
        dockerfile: Dockerfile
      depends_on:
        - mariadb
      restart: unless-stopped
      expose:
        - "9000"

volumes:
  volume_wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ntan/data/wordpress'
  volume_mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ntan/data/mariadb'
  
networks:
  inception:
    driver: bridge