echo "CREATE DATABASE IF NOT EXISTS ${SQL_DATABASE};
GRANT ALL PRIVILEGES ON *.* to 'root'@'localhost' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS '${SQL_USER}'@'%' IDENTIFIED BY '${SQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${SQL_DATABASE}.* TO '${SQL_USER}'@'%';
FLUSH PRIVILEGES; 
ALTER USER 'root'@'localhost' IDENTIFIED BY '${SQL_ROOT_PASSWORD}';" > /var/www/script2.sql