CREATE DATABASE IF NOT EXISTS Data1;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'secretpass';
GRANT ALL PRIVILEGES ON *.* to 'root'@'localhost' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'notroot'@'localhost' IDENTIFIED BY 'easypass';
GRANT ALL PRIVILEGES ON Data1.* TO 'notroot'@'%' IDENTIFIED BY 'easypass';

FLUSH PRIVILEGES;